# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'YLEpubReader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YLEpubReader
    pod 'Masonry'
    pod 'SSZipArchive'
    pod 'SVProgressHUD'
    pod 'DTCoreText', '1.6.20'
    pod 'MWPhotoBrowser', '~> 2.1.2'
    
  target 'YLEpubReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YLEpubReaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
